### ISSUE TITLE
Release signing key has expired

### ISSUE THREAD

**Issue by lpar** [s3-actions/s3cmd#13]
Just to let you know, the key used to sign the current release has expired.

![CleanShot 2024-03-07 at 10 00 07@2x](https://github.com/s3-actions/s3cmd/assets/857035/039b9038-9d5e-46e3-8464-a865dd3a0cc2)

**Comment by bluebrown** [comment]
Hi, thank you. Should I create a new release or can I resin this somehow?

**Comment by bluebrown** [comment]
i have released some other change. This should be ok now I think https://github.com/marketplace/actions/use-s3cmd
